### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by xxchaosxx210** [L4TTiCe/djangify#21]
I had to modify a few lines as was getting encoding exceptions

f = open(save_path + "." + extension, "w+", encoding="UTF-8")

and

with open(filepath, encoding="UTF-8") as fp:

to support UTF-8 encoding. Not sure if you want to add that and maybe an encoding option parameter in a newer version

**Comment by amartya-dev** [comment]
Adding specific encodings while reading the files might result into an error while dealing with different OS, we can keep it optional and accept it as a command-line argument
